packages:
  - "packages/*"

allowBuilds:
  esbuild: true

minimumReleaseAgeExclude:
  - '@ai-sdk/anthropic@2.0.87'
  - '@ai-sdk/google-vertex@3.0.152'
  - '@ai-sdk/google@2.0.82'
  - '@ai-sdk/openai-compatible@1.0.46'
  - '@ai-sdk/provider-utils@3.0.30'

onlyBuiltDependencies:
  - esbuild
